linters:
  disable-all: true
  enable:
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - vet

linters-settings:
  goimports:
    local-prefixes:
      github.com/cloudsigma/cloudsigma-sdk-go
      github.com/cloudsigma/terraform-provider-cloudsigma

output:
  format: tab

run:
  deadline: 10m
