name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Install tools
        run: make tools

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Generate changelog
        run: |
          mkdir -p .bin
          tools/bin/git-chglog -c .github/changelog/config.yaml -o .bin/DRAFT.md $(git describe --tags $(git rev-list --tags --max-count=1))

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release -f .github/goreleaser.yaml --clean --release-notes=.bin/DRAFT.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
